steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stem-splitter:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stem-splitter:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', 'stem-splitter',
        '--image', 'gcr.io/$PROJECT_ID/stem-splitter:$COMMIT_SHA',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--port', '8080',
        '--memory', '2Gi',
        '--cpu', '2',
        '--timeout', '1800s',
        '--concurrency', '1',
        '--set-env-vars', 'GCS_BUCKET_NAME=datascrape_amazonbestsellersincarengineoils,GCS_PROJECT_ID=$PROJECT_ID',
        '--allow-unauthenticated'
      ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/stem-splitter:$COMMIT_SHA'

# Set the logs behavior
options:
  logging: CLOUD_LOGGING_ONLY 